apiVersion: v1
kind: Service
metadata:
  name: bdmonedas-servicio
spec:
  selector:
    app: bdmonedas
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP